const sampleListings = [
  {
    title: "Modern PG with Great Amenities",
    userName: "Avani Sharma",
    phoneNumber: "8767529272",
    email: "avani.sharma@email.com",
    profileImage: {
      url: "https://example.com/profiles/avani.jpg",
      filename: "profiles/avani",
    },
    address: {
      street: "123 Anand Nagar",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789012",
    description: "A modern PG with access to a gym, ideal for health-conscious individuals.",
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: true,
    image: [
      {
        url: "https://www.nism.ac.in/wp-content/uploads/2022/04/Hostel-Room-1536x1024-1.jpg",
        filename: "listingimage",
      },
      {
        url: "https://i.ytimg.com/vi/K5TktBZt7no/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgWSg5MA8=&rs=AOn4CLAfVZanA0jXe0A_xbi2DnyDFzt0cg",
        filename: "listingimage",
      },
      {
        url: "https://kripalhomes.com/wp-content/uploads/2023/02/single-occupency-pg-in-ahmedabad.jpeg",
        filename: "listingimage",
      },
      {
        url: "https://5.imimg.com/data5/SE/NM/NW/SELLER-92780135/whatsapp-image-jpeg-500x500.jpeg",
        filename: "listingimage",
      },
      {
        url: "https://kripalhomes.com/wp-content/uploads/2023/02/single-occupency-pg-in-ahmedabad.jpeg",
        filename: "listingimage",
      },
    ],
    rent: 2000,
    pre_reservation_amount: 1000,
    location: "Anand Nagar, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "AC",
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Gym",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Meals",
      "CCTV",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7915, 19.9836], 
    },
  },
  {
    title: "Spacious PG for Students",
    userName: "Karan Kumar",
    phoneNumber: "9307004671",
    email: "karan.kumar@email.com",
    profileImage: {
      url: "https://example.com/profiles/karan.jpg",
      filename: "profiles/karan",
    },
    address: {
      street: "456 Gangapur Road",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789013",
    description: "Spacious accommodation perfect for students. Close to local colleges.",
    capacity: 4,
    bedrooms: 2,
    bathrooms: 1,
    availability: true,
    image: [
      {
        url: "https://i.ytimg.com/vi/K5TktBZt7no/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgWSg5MA8=&rs=AOn4CLAfVZanA0jXe0A_xbi2DnyDFzt0cg",
        filename: "listingimage",
      },
      {
        url: "https://www.isme.in/wp-content/uploads/2024/03/Hostel3.jpg",
        filename: "listingimage",
      },
      {
        url: "https://4.imimg.com/data4/XP/JB/MY-29402471/pg-rooms-500x500.jpg",
        filename: "listingimage",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnEEhD9tF0Nj-fTd9jNT-xsIDr-7vaYWrFZiNYkcW99r2vnubFQuwDZYoWIbm-ZW0nUBU&usqp=CAU",
        filename: "listingimage",
      },
      {
        url: "https://play-zelo-production.s3.ap-south-1.amazonaws.com/uploads/center/cover_photo/5d9ae2b309ba997ff97ea0bc/Zolo_Mystique_PG_in_Andheri_West_.jpeg",
        filename: "listingimage",
      },
    ],
    rent: 1800,
    pre_reservation_amount: 900,
    location: "Gangapur Road, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Water Purifier",
      "Power Backup",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7663, 19.9866], 
    },
  },
  {
    title: "Affordable PG with Food Options",
    userName: "Ishaan Shah",
    phoneNumber: "8766096954",
    email: "ishaan.shah@email.com",
    profileImage: {
      url: "https://example.com/profiles/ishaan.jpg",
      filename: "profiles/ishaan",
    },
    address: {
      street: "789 Dindori Road",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789014",
    description: "Affordable PG with great food options and 24/7 security.",
    capacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    availability: true,
    image: [
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/v1554802583/Website/Residences/Boston/1.jpg",
        filename: "listingimage",
      },
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/f_auto,q_auto/v1638174281/Website/CMS-Uploads/lhhdr9xadmfrpk1tdf7w.jpg",
        filename: "listingimage",
      },
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/f_auto,q_auto/v1638174287/Website/CMS-Uploads/enkwtscvtl9r6oe1dfr4.jpg",
        filename: "listingimage",
      },
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/v1613039987/Website/CMS-Uploads/ipsdl73ywcoy1ajbfasd.jpg",
        filename: "listingimage",
      },
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/v1554803482/Website/Residences/Toronto/2.jpg",
        filename: "listingimage",
      },
    ],
    rent: 2200,
    pre_reservation_amount: 1100,
    location: "Dindori Road, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "AC",
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Gym",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Meals",
      "Housekeeping",
      "CCTV",
      "Common Area",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7432, 20.0116], 
    },
  },
  {
    title: "Luxurious PG Near City Center",
    userName: "Ved Sharma",
    phoneNumber: "8767529272",
    email: "ved.sharma@email.com",
    profileImage: {
      url: "https://example.com/profiles/ved.jpg",
      filename: "profiles/ved",
    },
    address: {
      street: "901 City Center",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789015",
    description: "Luxurious PG offering a swimming pool and all modern amenities.",
    capacity: 5,
    bedrooms: 3,
    bathrooms: 2,
    availability: true,
    image: [
      {
        url: "https://content.jdmagicbox.com/comp/ghaziabad/w4/011pxx11.xx11.191217190807.e5w4/catalogue/rpn-boy-s-hostel-dasna-ghaziabad-hostels-adyayiouqi.jpg",
        filename: "listingimage",
      },
      {
        url: "https://content.jdmagicbox.com/comp/delhi/e6/011pxx11.xx11.150823143327.v8e6/catalogue/just-pg-satya-niketan-delhi-paying-guest-accommodations-naroqqjjj8.jpg",
        filename: "listingimage",
      },
      {
        url: "https://img.staticmb.com/mbphoto/pg/grd2/cropped_images/2023/Jul/18/Photo_h220_w280/GR2-384171-1820855_220_280.jpg",
        filename: "listingimage",
      },
      {
        url: "https://img.staticmb.com/mbphoto/pg/grd2/cropped_images/2021/Nov/28/Photo_h220_w280/GR2-254029-1191753_220_280.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/3189daf873abb59a8705eb68f77aea24/v0/medium/3_rk_-for-rent-sector_45-Gurgaon-bedroom.jpg",
        filename: "listingimage",
      },
    ],
    rent: 2400,
    pre_reservation_amount: 1200,
    location: "City Center, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "AC",
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Gym",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Meals",
      "CCTV",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7997, 19.9975], 
    },
  },
  {
    title: "Budget PG with Basic Amenities",
    userName: "Kiara Khanna",
    phoneNumber: "9307004671",
    email: "kiara.khanna@email.com",
    profileImage: {
      url: "https://example.com/profiles/kiara.jpg",
      filename: "profiles/kiara",
    },
    address: {
      street: "234 Sinnar",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789016",
    description: "A budget-friendly PG with all basic amenities.",
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: true,
    image: [
      {
        url: "https://img.cofynd.com/images/latest_images_2024/6770063e0d4b9f6553d269876b9c181aad356990.webp",
        filename: "listingimage",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGrf26B404R0i9Op5zIBvRPVgnXaCjGMCUsAHTiUQgXFt9gxG1H9pQmFwD6x1JBajE3Zo&usqp=CAU",
        filename: "listingimage",
      },
      {
        url: "https://www.safehousepg.in/uploads/girls-pg-sector-45-44-near-metro-gurgaon_(1).webp",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/dcadbb70818fcf7fb1b6ebcf247ecbba/v0/medium/3_rk_-for-rent-sector_39_gurgaon-Gurgaon-bedroom.jpg",
        filename: "listingimage",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5FrKc26hjHm2RDYwkLsMKPwKZEX1z9UH3TXFaKTXUxCj9W_rWNdOpAntZ8JOvEbPwUm8&usqp=CAU",
        filename: "listingimage",
      },
    ],
    rent: 1500,
    pre_reservation_amount: 750,
    location: "Sinnar, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Water Purifier",
      "Power Backup",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.8647, 19.8654], 
    },
  },
  {
    title: "Comfortable PG for Working Professionals",
    userName: "Suresh Kale",
    phoneNumber: "8766096954",
    email: "suresh.kale@email.com",
    profileImage: {
      url: "https://example.com/profiles/suresh.jpg",
      filename: "profiles/suresh",
    },
    address: {
      street: "567 Nashik Road",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789017",
    description: "Comfortable accommodation tailored for working professionals.",
    capacity: 4,
    bedrooms: 2,
    bathrooms: 1,
    availability: true,
    image: [
      {
        url: "https://metrocityliving.com/wp-content/uploads/2024/06/metrocity-shivtirth-nagar-banner-3.jpg",
        filename: "listingimage",
      },
      {
        url: "https://interlude.in/wp-content/uploads/2024/05/PG-Room-Decor-12-Essentials-list-to-turn-Your-PG-Room-into-a-Home-jpeg.webp",
        filename: "listingimage",
      },
      {
        url: "https://i.pinimg.com/236x/20/51/cf/2051cf5c647808e0cd184d9de842cee0.jpg",
        filename: "listingimage",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf4KLUFgAarBSKrDKUX8Gu6K0inaSCArEHkUGiB2zr1_c25oiNaojAzWLoMergXENPEhI&usqp=CAU",
        filename: "listingimage",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKBuMotCFhx3TIRuoEfuQO5GzqfgcTQEmp-o62X75dXXvKwICz0ZPbvlUADjlDDaD3Z4E&usqp=CAU",
        filename: "listingimage",
      },
    ],
    rent: 2300,
    pre_reservation_amount: 1150,
    location: "Nashik Road, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "AC",
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Gym",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Meals",
      "Housekeeping",
      "CCTV",
      "Common Area",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.8344, 19.9836], 
    },
  },
  {
    title: "Charming PG with Outdoor Space",
    userName: "Sachin Patil",
    phoneNumber: "8767529272",
    email: "sachin.patil@email.com",
    profileImage: {
      url: "https://example.com/profiles/sachin.jpg",
      filename: "profiles/sachin",
    },
    address: {
      street: "890 Panchavati",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789018",
    description: "Charming PG with a lovely garden space for relaxation.",
    capacity: 3,
    bedrooms: 2,
    bathrooms: 1,
    availability: false,
    image: [
      {
        url: "https://i.pinimg.com/236x/2c/e4/57/2ce457aaea703a02a6cfb3f0ddbfa156.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/a1650464897358aefa17e3e10f326497/v0/medium/3_rk_-for-rent-sector_71_gurgaon-Gurgaon-bedroom.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/427859c8da96aa9e1547b3d0a0c0c6fb/v0/medium/3_rk_-for-rent-choolaimedu-Chennai-bedroom.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/08ab7212cf44fec60fb0e5b45befe22e/v0/medium/3_rk_-for-rent-choolaimedu-Chennai-bedroom.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/858ddd3936f921844eca39b5afa39742/v0/medium/3_rk_-for-rent-kharadi-Pune-bedroom.jpg",
        filename: "listingimage",
      },
    ],
    rent: 1900,
    pre_reservation_amount: 950,
    location: "Panchavati, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Water Purifier",
      "Power Backup",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7844, 20.0039], 
    },
  },
  {
    title: "PG with Study Area",
    userName: "Pooja Kale",
    phoneNumber: "9307004671",
    email: "pooja.kale@email.com",
    profileImage: {
      url: "https://example.com/profiles/pooja.jpg",
      filename: "profiles/pooja",
    },
    address: {
      street: "345 College Road",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789019",
    description: "Ideal for students, featuring a quiet study area.",
    capacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: false,
    image: [
      {
        url: "https://img.staticmb.com/mbphoto/pg/grd2/cropped_images/2022/Jun/19/Photo_h220_w280/GR2-298167-1404351_220_280.jpeg",
        filename: "listingimage",
      },
      {
        url: "https://www.nism.ac.in/wp-content/uploads/2022/04/Hostel-Room-1536x1024-1.jpg",
        filename: "listingimage",
      },
      {
        url: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/502794286.jpg?k=3c2afe81f221230b9a4a9b3ed80c20cba000e2ddab08a5949cddd702f9969a1d&o=&hp=1",
        filename: "listingimage",
      },
      {
        url: "https://content3.jdmagicbox.com/comp/allahabad/j2/0532px532.x532.200205201228.i4j2/catalogue/v-r-s-l-paying-guest-lukarganj-allahabad-paying-guest-accommodations-pmu0fasjli.jpg",
        filename: "listingimage",
      },
      {
        url: "https://img.staticmb.com/mbphoto/pg/grd2/cropped_images/2023/Apr/08/Photo_h220_w280/GR2-362961-1716055_220_280.jpeg",
        filename: "listingimage",
      },
    ],
    rent: 2100,
    pre_reservation_amount: 1050,
    location: "College Road, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "AC",
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Gym",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Meals",
      "CCTV",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7844, 20.0039], 
    },
  },
  {
    title: "PG with Personal Lockers",
    userName: "Sandeep Nikam",
    phoneNumber: "8766096954",
    email: "sandeep.nikam@email.com",
    profileImage: {
      url: "https://example.com/profiles/sandeep.jpg",
      filename: "profiles/sandeep",
    },
    address: {
      street: "678 Nashik Road",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789020",
    description: "Personal lockers available for added security.",
    capacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    availability: true,
    image: [
      {
        url: "https://orionhostels.com/wp-content/uploads/2017/01/Single-room-1024x766.jpeg",
        filename: "listingimage",
      },
      {
        url: "https://orionhostels.com/wp-content/uploads/2017/01/WhatsApp-Image-2022-06-13-at-11.34.15-PM-1024x766.jpeg",
        filename: "listingimage",
      },
      {
        url: "https://orionhostels.com/wp-content/uploads/2017/01/triple-sharing-740x566.jpeg",
        filename: "listingimage",
      },
      {
        url: "https://orionhostels.com/wp-content/uploads/2017/01/WhatsApp-Image-2022-06-13-at-11.34.15-PM-1024x766.jpeg",
        filename: "listingimage",
      },
      {
        url: "https://img.staticmb.com/mbphoto/pg/grd2/cropped_images/2022/Jul/13/Photo_h400_w540/GR2-303095-1430115_400_540.jpg",
        filename: "listingimage",
      },
    ],
    rent: 2000,
    pre_reservation_amount: 1000,
    location: "Nashik Road, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Water Purifier",
      "Power Backup",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.8344, 19.9836], 
    },
  },
  {
    title: "PG with Cultural Activities",
    userName: "Rajesh Shinde",
    phoneNumber: "8767529272",
    email: "rajesh.shinde@email.com",
    profileImage: {
      url: "https://example.com/profiles/rajesh.jpg",
      filename: "profiles/rajesh",
    },
    address: {
      street: "901 Nashik",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789021",
    description: "Engage in various cultural activities during your stay.",
    capacity: 5,
    bedrooms: 3,
    bathrooms: 2,
    availability: true,
    image: [
      {
        url: "https://foto.hrsstatic.com/fotos/0/2/600/430/80/000000/http%3A%2F%2Ffoto-origin.hrsstatic.com%2Ffoto%2F9%2F8%2F7%2F3%2F987313%2F987313_z30_37341463.jpg/J1%2FbUXnmRVDAqGdsQjZHLw%3D%3D/500%2C333/6/Kyriad_Hotel_Nashik_by_OTHPL-Nashik-Standardzimmer-7-987313.jpg",
        filename: "listingimage",
      },
      {
        url: "https://images.trvl-media.com/lodging/34000000/33770000/33764000/33763922/af09d90b.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium",
        filename: "listingimage",
      },
      {
        url: "https://imagecdn.99acres.com/media1/26168/19/523379623M-1728379348626.jpg",
        filename: "listingimage",
      },
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/f_auto,q_auto/v1654170803/Website/CMS-Uploads/brkyfvbnfp6ger5ga2jm.jpg",
        filename: "listingimage",
      },
      {
        url: "https://assets.indiaonline.in/cat-default/450/single-occupancy-pg-pg-accomodation-and-hostels-for-boys.jpg",
        filename: "listingimage",
      },
    ],
    rent: 2200,
    pre_reservation_amount: 1100,
    location: "Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "AC",
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Gym",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Meals",
      "Housekeeping",
      "CCTV",
      "Common Area",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.8058, 19.9975], 
    },
  },
  {
    title: "PG with 24/7 Security",
    userName: "Priya Desai",
    phoneNumber: "9307004671",
    email: "priya.desai@email.com",
    profileImage: {
      url: "https://example.com/profiles/priya.jpg",
      filename: "profiles/priya",
    },
    address: {
      street: "123 Anand Nagar",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789022",
    description: "PG with 24/7 security and all modern amenities.",
    capacity: 5,
    bedrooms: 3,
    bathrooms: 2,
    availability: true,
    image: [
      {
        url: "https://content.jdmagicbox.com/comp/ghaziabad/w4/011pxx11.xx11.191217190807.e5w4/catalogue/rpn-boy-s-hostel-dasna-ghaziabad-hostels-adyayiouqi.jpg",
        filename: "listingimage",
      },
      {
        url: "https://content.jdmagicbox.com/comp/delhi/e6/011pxx11.xx11.150823143327.v8e6/catalogue/just-pg-satya-niketan-delhi-paying-guest-accommodations-naroqqjjj8.jpg",
        filename: "listingimage",
      },
      {
        url: "https://img.staticmb.com/mbphoto/pg/grd2/cropped_images/2023/Jul/18/Photo_h220_w280/GR2-384171-1820855_220_280.jpg",
        filename: "listingimage",
      },
      {
        url: "https://img.staticmb.com/mbphoto/pg/grd2/cropped_images/2021/Nov/28/Photo_h220_w280/GR2-254029-1191753_220_280.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/3189daf873abb59a8705eb68f77aea24/v0/medium/3_rk_-for-rent-sector_45-Gurgaon-bedroom.jpg",
        filename: "listingimage",
      },
    ],
    rent: 2400,
    pre_reservation_amount: 1200,
    location: "Anand Nagar, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "AC",
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Gym",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Meals",
      "CCTV",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7915, 19.9836], 
    },
  },
  {
    title: "PG with Modern Amenities",
    userName: "Rahul Verma",
    phoneNumber: "8766096954",
    email: "rahul.verma@email.com",
    profileImage: {
      url: "https://example.com/profiles/rahul.jpg",
      filename: "profiles/rahul",
    },
    address: {
      street: "456 Gangapur Road",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789023",
    description: "PG with all modern amenities and close to local colleges.",
    capacity: 4,
    bedrooms: 2,
    bathrooms: 1,
    availability: true,
    image: [
      {
        url: "https://i.ytimg.com/vi/K5TktBZt7no/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgWSg5MA8=&rs=AOn4CLAfVZanA0jXe0A_xbi2DnyDFzt0cg",
        filename: "listingimage",
      },
      {
        url: "https://www.isme.in/wp-content/uploads/2024/03/Hostel3.jpg",
        filename: "listingimage",
      },
      {
        url: "https://4.imimg.com/data4/XP/JB/MY-29402471/pg-rooms-500x500.jpg",
        filename: "listingimage",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnEEhD9tF0Nj-fTd9jNT-xsIDr-7vaYWrFZiNYkcW99r2vnubFQuwDZYoWIbm-ZW0nUBU&usqp=CAU",
        filename: "listingimage",
      },
      {
        url: "https://play-zelo-production.s3.ap-south-1.amazonaws.com/uploads/center/cover_photo/5d9ae2b309ba997ff97ea0bc/Zolo_Mystique_PG_in_Andheri_West_.jpeg",
        filename: "listingimage",
      },
    ],
    rent: 1800,
    pre_reservation_amount: 900,
    location: "Gangapur Road, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Water Purifier",
      "Power Backup",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7663, 19.9866], 
    },
  },
  {
    title: "PG with Home-like Environment",
    userName: "Neha Patel",
    phoneNumber: "8767529272",
    email: "neha.patel@email.com",
    profileImage: {
      url: "https://example.com/profiles/neha.jpg",
      filename: "profiles/neha",
    },
    address: {
      street: "789 Dindori Road",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789024",
    description: "PG with a home-like environment and great food options.",
    capacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    availability: true,
    image: [
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/v1554802583/Website/Residences/Boston/1.jpg",
        filename: "listingimage",
      },
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/f_auto,q_auto/v1638174281/Website/CMS-Uploads/lhhdr9xadmfrpk1tdf7w.jpg",
        filename: "listingimage",
      },
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/f_auto,q_auto/v1638174287/Website/CMS-Uploads/enkwtscvtl9r6oe1dfr4.jpg",
        filename: "listingimage",
      },
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/v1613039987/Website/CMS-Uploads/ipsdl73ywcoy1ajbfasd.jpg",
        filename: "listingimage",
      },
      {
        url: "https://res.cloudinary.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/v1554803482/Website/Residences/Toronto/2.jpg",
        filename: "listingimage",
      },
    ],
    rent: 1900,
    pre_reservation_amount: 950,
    location: "Dindori Road, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "AC",
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Gym",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Meals",
      "Housekeeping",
      "CCTV",
      "Common Area",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7432, 20.0116], 
    },
  },
  {
    title: "PG with Professional Management",
    userName: "Amit Singh",
    phoneNumber: "9307004671",
    email: "amit.singh@email.com",
    profileImage: {
      url: "https://example.com/profiles/amit.jpg",
      filename: "profiles/amit",
    },
    address: {
      street: "567 Nashik Road",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789025",
    description: "PG with professional management and close to local colleges.",
    capacity: 4,
    bedrooms: 2,
    bathrooms: 1,
    availability: true,
    image: [
      {
        url: "https://metrocityliving.com/wp-content/uploads/2024/06/metrocity-shivtirth-nagar-banner-3.jpg",
        filename: "listingimage",
      },
      {
        url: "https://interlude.in/wp-content/uploads/2024/05/PG-Room-Decor-12-Essentials-list-to-turn-Your-PG-Room-into-a-Home-jpeg.webp",
        filename: "listingimage",
      },
      {
        url: "https://i.pinimg.com/236x/20/51/cf/2051cf5c647808e0cd184d9de842cee0.jpg",
        filename: "listingimage",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf4KLUFgAarBSKrDKUX8Gu6K0inaSCArEHkUGiB2zr1_c25oiNaojAzWLoMergXENPEhI&usqp=CAU",
        filename: "listingimage",
      },
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKBuMotCFhx3TIRuoEfuQO5GzqfgcTQEmp-o62X75dXXvKwICz0ZPbvlUADjlDDaD3Z4E&usqp=CAU",
        filename: "listingimage",
      },
    ],
    rent: 2300,
    pre_reservation_amount: 1150,
    location: "Nashik Road, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "AC",
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Gym",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Meals",
      "Housekeeping",
      "CCTV",
      "Common Area",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.8344, 19.9836], 
    },
  },
  {
    title: "PG with Student-Friendly Atmosphere",
    userName: "Deepika Mehta",
    phoneNumber: "8766096954",
    email: "deepika.mehta@email.com",
    profileImage: {
      url: "https://example.com/profiles/deepika.jpg",
      filename: "profiles/deepika",
    },
    address: {
      street: "890 Panchavati",
      city: "Nashik",
      state: "Maharashtra",
      zipCode: "422009",
    },
    adharCard: "123456789026",
    description: "PG with a student-friendly atmosphere and great food options.",
    capacity: 3,
    bedrooms: 2,
    bathrooms: 1,
    availability: false,
    image: [
      {
        url: "https://i.pinimg.com/236x/2c/e4/57/2ce457aaea703a02a6cfb3f0ddbfa156.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/a1650464897358aefa17e3e10f326497/v0/medium/3_rk_-for-rent-sector_71_gurgaon-Gurgaon-bedroom.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/427859c8da96aa9e1547b3d0a0c0c6fb/v0/medium/3_rk_-for-rent-choolaimedu-Chennai-bedroom.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/08ab7212cf44fec60fb0e5b45befe22e/v0/medium/3_rk_-for-rent-choolaimedu-Chennai-bedroom.jpg",
        filename: "listingimage",
      },
      {
        url: "https://housing-images.n7net.in/01c16c28/858ddd3936f921844eca39b5afa39742/v0/medium/3_rk_-for-rent-kharadi-Pune-bedroom.jpg",
        filename: "listingimage",
      },
    ],
    rent: 1700,
    pre_reservation_amount: 850,
    location: "Panchavati, Nashik, Maharashtra, India",
    country: "India",
    amenities: [
      "WiFi",
      "Parking",
      "Kitchen",
      "TV",
      "Laundry",
      "Security",
      "Hot Water",
      "Study Table",
      "Wardrobe",
      "Bed",
      "Water Purifier",
      "Power Backup",
    ],
    geometry: {
      type: "Point",
      coordinates: [73.7844, 20.0039], 
    },
  },
];

module.exports = { data: sampleListings };